on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    name: Release and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install the dependencies
        run: npm i

      - name: temp deploy fix got ovsx
        run: npm i semver
        # this will be fixed by next release...just don't want to re-tag and re-publish

      - name: Install vsce and Open VSX
        run: npm i -g vsce ovsx

      - name: Publish to VS Code Marketplace
        id: pub_vsce
        run: |
          vsce publish -p ${{ secrets.VSCE_TOKEN }}
        continue-on-error: true
        # TODO: remove this ^

      - name: Publish to Open VSX
        id: pub_ovsx
        run: |
          npx ovsx publish -p ${{ secrets.OPEN_VSX }}
        continue-on-error: true
        # TODO: remove this ^
